name: tukitaki_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6595
  flutter_easyloading: ^3.0.5
  # get_storage: ^2.0.3
  sweetsheet: ^0.4.0
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  dio: ^4.0.6
  uuid: ^3.0.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
      - assets/logo/
      - assets/fonts/
  uses-material-design: true

