// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXkESufe98PJsAM8fXFFWGUEGAVVQp7qM',
    appId: '1:675387280298:web:1c394443cd2e3f954079d3',
    messagingSenderId: '675387280298',
    projectId: 'tukitaki-b3b05',
    authDomain: 'tukitaki-b3b05.firebaseapp.com',
    storageBucket: 'tukitaki-b3b05.appspot.com',
    measurementId: 'G-CD7Q2SMXT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1fW_LVaKFxYizImyhEhBhfzgTqrgFMKo',
    appId: '1:675387280298:android:065bfdab8645eed54079d3',
    messagingSenderId: '675387280298',
    projectId: 'tukitaki-b3b05',
    storageBucket: 'tukitaki-b3b05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90bYhTuRUgM61ibDwojgg17TSN74gFCQ',
    appId: '1:675387280298:ios:ec5a5fd667bda48a4079d3',
    messagingSenderId: '675387280298',
    projectId: 'tukitaki-b3b05',
    storageBucket: 'tukitaki-b3b05.appspot.com',
    iosClientId: '675387280298-eh41lshdrhnf576ciilis2eegcvf04ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.tukitakiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90bYhTuRUgM61ibDwojgg17TSN74gFCQ',
    appId: '1:675387280298:ios:ec5a5fd667bda48a4079d3',
    messagingSenderId: '675387280298',
    projectId: 'tukitaki-b3b05',
    storageBucket: 'tukitaki-b3b05.appspot.com',
    iosClientId: '675387280298-eh41lshdrhnf576ciilis2eegcvf04ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.tukitakiFlutter',
  );
}
